#!/usr/bin/env python3
"""
Create Jira tickets from a CSV file generated by standardTicketCreator.py.

This script reads a per-team CSV file and creates tickets deterministically
via the Python Jira client, avoiding the error-prone manual loop required
when using Claude Code with the Jira MCP.

Usage:
    python createTicketsFromCsv.py q3-2026-Queueless.csv teams.xlsx      # preview (dry-run)
    python createTicketsFromCsv.py q3-2026-Queueless.csv teams.xlsx -c   # create tickets
"""

import argparse
import csv
import sys
import jira
from colorama import init, Fore, Style

from libraries.jiraToolsConfig import load_config
from libraries.jiraTicketTools import read_custom_fields_mapping, create_jira_ticket


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Create Jira tickets from a CSV file generated by standardTicketCreator.py"
    )
    parser.add_argument(
        "csv_file",
        help="CSV file with ticket data (e.g., q3-2026-Queueless.csv)"
    )
    parser.add_argument(
        "excel_file",
        help="Excel config file (teams.xlsx) needed to resolve custom field IDs"
    )
    parser.add_argument(
        "-c", "--create",
        action="store_true",
        help="Actually create tickets in Jira (default: dry-run only, prints what would be created)"
    )
    return parser.parse_args()


def create_tickets_from_csv(csv_file, excel_file, jira_client, custom_fields_mapping, dry_run=False):
    """
    Read CSV and create Jira tickets.

    Args:
        csv_file: Path to CSV file
        excel_file: Path to Excel config file (for logging in error messages)
        jira_client: Jira client
        custom_fields_mapping: Custom field ID mappings
        dry_run: If True, print what would be created without calling Jira

    Returns:
        List of created ticket keys
    """
    created_tickets = []

    try:
        with open(csv_file, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            if not reader.fieldnames:
                print(f"{Fore.RED}Error: CSV file is empty{Style.RESET_ALL}")
                return created_tickets

            row_count = 0
            for row in reader:
                row_count += 1
                summary = row.get('Summary', '').strip()
                if not summary:
                    print(f"{Fore.YELLOW}Warning: Row {row_count} has empty Summary, skipping{Style.RESET_ALL}")
                    continue

                project_key = row.get('Project Key', '').strip()
                issue_type = row.get('Issue Type', 'Task').strip()
                description = row.get('Description', '').strip()

                # Collect additional fields (all columns except the standard ones)
                standard_cols = {'Summary', 'Issue Type', 'Project Key', 'Description'}
                additional_fields = {k: v.strip() for k, v in row.items() if k not in standard_cols and v.strip()}

                if dry_run:
                    print(f"\n{Fore.CYAN}[DRY RUN] Would create ticket:{Style.RESET_ALL}")
                    print(f"  Summary: {summary}")
                    print(f"  Project: {project_key}")
                    print(f"  Type: {issue_type}")
                    if additional_fields:
                        print(f"  Additional fields:")
                        for k, v in additional_fields.items():
                            print(f"    {k}: {v}")
                else:
                    try:
                        ticket_key = create_jira_ticket(
                            jira_client,
                            project_key,
                            issue_type,
                            summary,
                            description,
                            excel_file=excel_file,
                            **additional_fields
                        )
                        created_tickets.append(ticket_key)
                        print(f"{Fore.GREEN}✓ Created {ticket_key}: {summary}{Style.RESET_ALL}")
                    except Exception as e:
                        print(f"{Fore.RED}✗ Failed to create ticket (row {row_count}): {e}{Style.RESET_ALL}")

            if dry_run:
                print(f"\n{Fore.CYAN}Total rows: {row_count}{Style.RESET_ALL}")
            else:
                print(f"\n{Fore.GREEN}Created {len(created_tickets)} ticket(s){Style.RESET_ALL}")

    except FileNotFoundError:
        print(f"{Fore.RED}Error: CSV file not found: {csv_file}{Style.RESET_ALL}")
        return created_tickets
    except Exception as e:
        print(f"{Fore.RED}Error reading CSV: {e}{Style.RESET_ALL}")
        return created_tickets

    return created_tickets


def main():
    init()

    args = parse_arguments()

    # Load Jira config
    config = load_config()
    if not config:
        print(f"{Fore.RED}Error: Failed to load Jira config{Style.RESET_ALL}")
        sys.exit(1)

    # Initialize Jira client
    try:
        jira_client = jira.JIRA(
            config["jira_server"],
            token_auth=config["personal_access_token"],
        )
    except Exception as e:
        print(f"{Fore.RED}Error connecting to Jira: {e}{Style.RESET_ALL}")
        sys.exit(1)

    # Load custom field mappings
    try:
        custom_fields_mapping = read_custom_fields_mapping(args.excel_file)
    except Exception as e:
        print(f"{Fore.YELLOW}Warning: Could not load custom field mappings: {e}{Style.RESET_ALL}")
        custom_fields_mapping = {}

    # Create tickets (default: dry-run only)
    dry_run = not args.create
    if dry_run:
        print(f"{Fore.YELLOW}[DRY RUN MODE] No tickets will be created. Pass -c/--create to actually create.{Style.RESET_ALL}\n")
    print(f"{Fore.CYAN}Reading tickets from {args.csv_file}...{Style.RESET_ALL}\n")
    created_tickets = create_tickets_from_csv(
        args.csv_file,
        args.excel_file,
        jira_client,
        custom_fields_mapping,
        dry_run=dry_run
    )

    if not dry_run and created_tickets:
        print(f"\n{Fore.GREEN}Summary:{Style.RESET_ALL}")
        print(f"  Created {len(created_tickets)} ticket(s)")
        for key in created_tickets:
            print(f"    {key}")


if __name__ == "__main__":
    main()
